create table "public"."Items" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "userId" uuid not null,
    "category" text not null,
    "image" text not null,
    "title" text not null,
    "description" text not null,
    "method" text not null,
    "available" boolean not null default true
);


CREATE UNIQUE INDEX "Items_pkey" ON public."Items" USING btree (id);

alter table "public"."Items" add constraint "Items_pkey" PRIMARY KEY using index "Items_pkey";

alter table "public"."Items" add constraint "Items_userId_fkey" FOREIGN KEY ("userId") REFERENCES auth.users(id) ON UPDATE CASCADE ON DELETE SET NULL not valid;

alter table "public"."Items" validate constraint "Items_userId_fkey";

grant delete on table "public"."Items" to "anon";

grant insert on table "public"."Items" to "anon";

grant references on table "public"."Items" to "anon";

grant select on table "public"."Items" to "anon";

grant trigger on table "public"."Items" to "anon";

grant truncate on table "public"."Items" to "anon";

grant update on table "public"."Items" to "anon";

grant delete on table "public"."Items" to "authenticated";

grant insert on table "public"."Items" to "authenticated";

grant references on table "public"."Items" to "authenticated";

grant select on table "public"."Items" to "authenticated";

grant trigger on table "public"."Items" to "authenticated";

grant truncate on table "public"."Items" to "authenticated";

grant update on table "public"."Items" to "authenticated";

grant delete on table "public"."Items" to "service_role";

grant insert on table "public"."Items" to "service_role";

grant references on table "public"."Items" to "service_role";

grant select on table "public"."Items" to "service_role";

grant trigger on table "public"."Items" to "service_role";

grant truncate on table "public"."Items" to "service_role";

grant update on table "public"."Items" to "service_role";


