create table "public"."Accessories" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "itemId" bigint not null,
    "subcategory" text not null,
    "weight" text not null,
    "material" text not null,
    "condition" text not null,
    "color" text not null
);

alter table "public"."Accessories" enable row level security;

create table "public"."Clothing" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "itemId" bigint not null,
    "subcategory" text not null
    "size" text not null,
    "weight" text not null,
    "fabric" text not null,
    "condition" text not null,
    "color" text not null,
);


alter table "public"."Clothing" enable row level security;

create table "public"."Shoes" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "itemId" bigint not null,
    "subcategory" text not null,
    "size" bigint not null,
    "weight" text not null,
    "fabric" text not null,
    "length" text not null,
    "condition" text not null,
    "color" text not null
);


alter table "public"."Shoes" enable row level security;

CREATE UNIQUE INDEX "Accessories_pkey" ON public."Accessories" USING btree (id);

CREATE UNIQUE INDEX "Clothing_pkey" ON public."Clothing" USING btree (id);

CREATE UNIQUE INDEX "Shoes_pkey" ON public."Shoes" USING btree (id);

alter table "public"."Accessories" add constraint "Accessories_pkey" PRIMARY KEY using index "Accessories_pkey";

alter table "public"."Clothing" add constraint "Clothing_pkey" PRIMARY KEY using index "Clothing_pkey";

alter table "public"."Shoes" add constraint "Shoes_pkey" PRIMARY KEY using index "Shoes_pkey";

alter table "public"."Accessories" add constraint "Accessories_itemId_fkey" FOREIGN KEY ("itemId") REFERENCES "Items"(id) ON UPDATE CASCADE ON DELETE SET NULL not valid;

alter table "public"."Accessories" validate constraint "Accessories_itemId_fkey";

alter table "public"."Clothing" add constraint "Clothing_itemId_fkey" FOREIGN KEY ("itemId") REFERENCES "Items"(id) ON UPDATE CASCADE ON DELETE SET NULL not valid;

alter table "public"."Clothing" validate constraint "Clothing_itemId_fkey";

alter table "public"."Shoes" add constraint "Shoes_itemId_fkey" FOREIGN KEY ("itemId") REFERENCES "Items"(id) ON UPDATE CASCADE ON DELETE SET NULL not valid;

alter table "public"."Shoes" validate constraint "Shoes_itemId_fkey";

grant delete on table "public"."Accessories" to "anon";

grant insert on table "public"."Accessories" to "anon";

grant references on table "public"."Accessories" to "anon";

grant select on table "public"."Accessories" to "anon";

grant trigger on table "public"."Accessories" to "anon";

grant truncate on table "public"."Accessories" to "anon";

grant update on table "public"."Accessories" to "anon";

grant delete on table "public"."Accessories" to "authenticated";

grant insert on table "public"."Accessories" to "authenticated";

grant references on table "public"."Accessories" to "authenticated";

grant select on table "public"."Accessories" to "authenticated";

grant trigger on table "public"."Accessories" to "authenticated";

grant truncate on table "public"."Accessories" to "authenticated";

grant update on table "public"."Accessories" to "authenticated";

grant delete on table "public"."Accessories" to "service_role";

grant insert on table "public"."Accessories" to "service_role";

grant references on table "public"."Accessories" to "service_role";

grant select on table "public"."Accessories" to "service_role";

grant trigger on table "public"."Accessories" to "service_role";

grant truncate on table "public"."Accessories" to "service_role";

grant update on table "public"."Accessories" to "service_role";

grant delete on table "public"."Clothing" to "anon";

grant insert on table "public"."Clothing" to "anon";

grant references on table "public"."Clothing" to "anon";

grant select on table "public"."Clothing" to "anon";

grant trigger on table "public"."Clothing" to "anon";

grant truncate on table "public"."Clothing" to "anon";

grant update on table "public"."Clothing" to "anon";

grant delete on table "public"."Clothing" to "authenticated";

grant insert on table "public"."Clothing" to "authenticated";

grant references on table "public"."Clothing" to "authenticated";

grant select on table "public"."Clothing" to "authenticated";

grant trigger on table "public"."Clothing" to "authenticated";

grant truncate on table "public"."Clothing" to "authenticated";

grant update on table "public"."Clothing" to "authenticated";

grant delete on table "public"."Clothing" to "service_role";

grant insert on table "public"."Clothing" to "service_role";

grant references on table "public"."Clothing" to "service_role";

grant select on table "public"."Clothing" to "service_role";

grant trigger on table "public"."Clothing" to "service_role";

grant truncate on table "public"."Clothing" to "service_role";

grant update on table "public"."Clothing" to "service_role";

grant delete on table "public"."Shoes" to "anon";

grant insert on table "public"."Shoes" to "anon";

grant references on table "public"."Shoes" to "anon";

grant select on table "public"."Shoes" to "anon";

grant trigger on table "public"."Shoes" to "anon";

grant truncate on table "public"."Shoes" to "anon";

grant update on table "public"."Shoes" to "anon";

grant delete on table "public"."Shoes" to "authenticated";

grant insert on table "public"."Shoes" to "authenticated";

grant references on table "public"."Shoes" to "authenticated";

grant select on table "public"."Shoes" to "authenticated";

grant trigger on table "public"."Shoes" to "authenticated";

grant truncate on table "public"."Shoes" to "authenticated";

grant update on table "public"."Shoes" to "authenticated";

grant delete on table "public"."Shoes" to "service_role";

grant insert on table "public"."Shoes" to "service_role";

grant references on table "public"."Shoes" to "service_role";

grant select on table "public"."Shoes" to "service_role";

grant trigger on table "public"."Shoes" to "service_role";

grant truncate on table "public"."Shoes" to "service_role";

grant update on table "public"."Shoes" to "service_role";


