create table "public"."Accessories" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "itemId" bigint not null,
    "subcategory" text not null,
    "weight" text not null,
    "material" text not null,
    "condition" text not null,
    "color" text not null
);


create table "public"."CalendarDates" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "userId" uuid not null,
    "item" text not null,
    "itemType" text not null,
    "dates" jsonb not null
);


alter table "public"."CalendarDates" enable row level security;

create table "public"."Clothing" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "itemId" bigint not null,
    "subcategory" text not null,
    "size" text not null,
    "weight" text not null,
    "fabric" text not null,
    "condition" text not null,
    "color" text not null
);


create table "public"."Conversations" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "userId_1" uuid,
    "userId_2" uuid
);


create table "public"."Groups" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "ambassadorId" uuid not null,
    "name" text not null,
    "description" text not null,
    "location" text not null,
    "rules" text not null,
    "numberOfMem" bigint not null,
    "avatar" text not null
);


create table "public"."ItemConversions" (
    "id" bigint generated by default as identity not null,
    "name" text not null,
    "litres" bigint not null,
    "carbon" double precision not null,
    "scalable" boolean not null,
    "category" text
);


create table "public"."Items" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "userId" uuid not null,
    "category" text not null,
    "image" text not null,
    "title" text not null,
    "description" text not null,
    "method" text not null,
    "available" boolean not null default true,
    "tradeCount" bigint default '0'::bigint,
    "unavailableDates" jsonb
);


create table "public"."JoinRequests" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "userId" uuid not null,
    "groupId" bigint not null,
    "message" text not null default ''::text,
    "status" text not null default 'Pending'::text
);


create table "public"."Messages" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "conversationId" bigint not null,
    "senderId" uuid not null,
    "text" text,
    "itemId" bigint,
    "loanDates" jsonb default 'null'::jsonb,
    "messageType" text not null,
    "decision" text
);


create table "public"."Shoes" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "itemId" bigint not null,
    "subcategory" text not null,
    "size" text not null,
    "weight" text not null,
    "fabric" text not null,
    "shoelength" text not null,
    "condition" text not null,
    "color" text not null
);


create table "public"."Wishlist" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "userId" uuid,
    "itemId" bigint
);


CREATE UNIQUE INDEX "Accessories_pkey" ON public."Accessories" USING btree (id);

CREATE UNIQUE INDEX "CalendarDates_pkey" ON public."CalendarDates" USING btree (id);

CREATE UNIQUE INDEX "Conversations_pkey" ON public."Conversations" USING btree (id);

CREATE UNIQUE INDEX "ItemConversions_name_key" ON public."ItemConversions" USING btree (name);

CREATE UNIQUE INDEX "ItemConversions_pkey" ON public."ItemConversions" USING btree (id);

CREATE UNIQUE INDEX "Items_pkey" ON public."Items" USING btree (id);

CREATE UNIQUE INDEX "JoinRequests_pkey" ON public."JoinRequests" USING btree (id);

CREATE UNIQUE INDEX "Messages_pkey" ON public."Messages" USING btree (id);

CREATE UNIQUE INDEX "Wishlist_pkey" ON public."Wishlist" USING btree (id);

CREATE UNIQUE INDEX clothing_pkey ON public."Clothing" USING btree (id);

CREATE UNIQUE INDEX groups_pkey ON public."Groups" USING btree (id);

CREATE UNIQUE INDEX shoes_pkey ON public."Shoes" USING btree (id);

alter table "public"."Accessories" add constraint "Accessories_pkey" PRIMARY KEY using index "Accessories_pkey";

alter table "public"."CalendarDates" add constraint "CalendarDates_pkey" PRIMARY KEY using index "CalendarDates_pkey";

alter table "public"."Clothing" add constraint "clothing_pkey" PRIMARY KEY using index "clothing_pkey";

alter table "public"."Conversations" add constraint "Conversations_pkey" PRIMARY KEY using index "Conversations_pkey";

alter table "public"."Groups" add constraint "groups_pkey" PRIMARY KEY using index "groups_pkey";

alter table "public"."ItemConversions" add constraint "ItemConversions_pkey" PRIMARY KEY using index "ItemConversions_pkey";

alter table "public"."Items" add constraint "Items_pkey" PRIMARY KEY using index "Items_pkey";

alter table "public"."JoinRequests" add constraint "JoinRequests_pkey" PRIMARY KEY using index "JoinRequests_pkey";

alter table "public"."Messages" add constraint "Messages_pkey" PRIMARY KEY using index "Messages_pkey";

alter table "public"."Shoes" add constraint "shoes_pkey" PRIMARY KEY using index "shoes_pkey";

alter table "public"."Wishlist" add constraint "Wishlist_pkey" PRIMARY KEY using index "Wishlist_pkey";

alter table "public"."Accessories" add constraint "Accessories_itemId_fkey" FOREIGN KEY ("itemId") REFERENCES "Items"(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."Accessories" validate constraint "Accessories_itemId_fkey";

alter table "public"."CalendarDates" add constraint "CalendarDates_userId_fkey" FOREIGN KEY ("userId") REFERENCES auth.users(id) not valid;

alter table "public"."CalendarDates" validate constraint "CalendarDates_userId_fkey";

alter table "public"."Clothing" add constraint "clothing_itemid_fkey" FOREIGN KEY ("itemId") REFERENCES "Items"(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."Clothing" validate constraint "clothing_itemid_fkey";

alter table "public"."Conversations" add constraint "Conversations_userId_1_fkey" FOREIGN KEY ("userId_1") REFERENCES auth.users(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."Conversations" validate constraint "Conversations_userId_1_fkey";

alter table "public"."Conversations" add constraint "Conversations_userId_2_fkey" FOREIGN KEY ("userId_2") REFERENCES auth.users(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."Conversations" validate constraint "Conversations_userId_2_fkey";

alter table "public"."Groups" add constraint "groups_ambassadorid_fkey" FOREIGN KEY ("ambassadorId") REFERENCES auth.users(id) ON UPDATE CASCADE ON DELETE SET NULL not valid;

alter table "public"."Groups" validate constraint "groups_ambassadorid_fkey";

alter table "public"."ItemConversions" add constraint "ItemConversions_name_key" UNIQUE using index "ItemConversions_name_key";

alter table "public"."Items" add constraint "Items_userId_fkey" FOREIGN KEY ("userId") REFERENCES auth.users(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."Items" validate constraint "Items_userId_fkey";

alter table "public"."JoinRequests" add constraint "JoinRequests_groupId_fkey" FOREIGN KEY ("groupId") REFERENCES "Groups"(id) ON UPDATE CASCADE ON DELETE SET NULL not valid;

alter table "public"."JoinRequests" validate constraint "JoinRequests_groupId_fkey";

alter table "public"."JoinRequests" add constraint "JoinRequests_userId_fkey" FOREIGN KEY ("userId") REFERENCES auth.users(id) ON UPDATE CASCADE ON DELETE SET NULL not valid;

alter table "public"."JoinRequests" validate constraint "JoinRequests_userId_fkey";

alter table "public"."Messages" add constraint "Messages_conversationId_fkey" FOREIGN KEY ("conversationId") REFERENCES "Conversations"(id) not valid;

alter table "public"."Messages" validate constraint "Messages_conversationId_fkey";

alter table "public"."Messages" add constraint "Messages_itemId_fkey" FOREIGN KEY ("itemId") REFERENCES "Items"(id) not valid;

alter table "public"."Messages" validate constraint "Messages_itemId_fkey";

alter table "public"."Messages" add constraint "Messages_senderId_fkey" FOREIGN KEY ("senderId") REFERENCES auth.users(id) not valid;

alter table "public"."Messages" validate constraint "Messages_senderId_fkey";

alter table "public"."Shoes" add constraint "shoes_itemid_fkey" FOREIGN KEY ("itemId") REFERENCES "Items"(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."Shoes" validate constraint "shoes_itemid_fkey";

alter table "public"."Wishlist" add constraint "Wishlist_itemId_fkey" FOREIGN KEY ("itemId") REFERENCES "Items"(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."Wishlist" validate constraint "Wishlist_itemId_fkey";

alter table "public"."Wishlist" add constraint "Wishlist_userId_fkey" FOREIGN KEY ("userId") REFERENCES auth.users(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."Wishlist" validate constraint "Wishlist_userId_fkey";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.handle_new_user()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
begin
  insert into public.users (id)
  values (new.id);
  return new;
end;
$function$
;

grant delete on table "public"."Accessories" to "anon";

grant insert on table "public"."Accessories" to "anon";

grant references on table "public"."Accessories" to "anon";

grant select on table "public"."Accessories" to "anon";

grant trigger on table "public"."Accessories" to "anon";

grant truncate on table "public"."Accessories" to "anon";

grant update on table "public"."Accessories" to "anon";

grant delete on table "public"."Accessories" to "authenticated";

grant insert on table "public"."Accessories" to "authenticated";

grant references on table "public"."Accessories" to "authenticated";

grant select on table "public"."Accessories" to "authenticated";

grant trigger on table "public"."Accessories" to "authenticated";

grant truncate on table "public"."Accessories" to "authenticated";

grant update on table "public"."Accessories" to "authenticated";

grant delete on table "public"."Accessories" to "service_role";

grant insert on table "public"."Accessories" to "service_role";

grant references on table "public"."Accessories" to "service_role";

grant select on table "public"."Accessories" to "service_role";

grant trigger on table "public"."Accessories" to "service_role";

grant truncate on table "public"."Accessories" to "service_role";

grant update on table "public"."Accessories" to "service_role";

grant delete on table "public"."CalendarDates" to "anon";

grant insert on table "public"."CalendarDates" to "anon";

grant references on table "public"."CalendarDates" to "anon";

grant select on table "public"."CalendarDates" to "anon";

grant trigger on table "public"."CalendarDates" to "anon";

grant truncate on table "public"."CalendarDates" to "anon";

grant update on table "public"."CalendarDates" to "anon";

grant delete on table "public"."CalendarDates" to "authenticated";

grant insert on table "public"."CalendarDates" to "authenticated";

grant references on table "public"."CalendarDates" to "authenticated";

grant select on table "public"."CalendarDates" to "authenticated";

grant trigger on table "public"."CalendarDates" to "authenticated";

grant truncate on table "public"."CalendarDates" to "authenticated";

grant update on table "public"."CalendarDates" to "authenticated";

grant delete on table "public"."CalendarDates" to "service_role";

grant insert on table "public"."CalendarDates" to "service_role";

grant references on table "public"."CalendarDates" to "service_role";

grant select on table "public"."CalendarDates" to "service_role";

grant trigger on table "public"."CalendarDates" to "service_role";

grant truncate on table "public"."CalendarDates" to "service_role";

grant update on table "public"."CalendarDates" to "service_role";

grant delete on table "public"."Clothing" to "anon";

grant insert on table "public"."Clothing" to "anon";

grant references on table "public"."Clothing" to "anon";

grant select on table "public"."Clothing" to "anon";

grant trigger on table "public"."Clothing" to "anon";

grant truncate on table "public"."Clothing" to "anon";

grant update on table "public"."Clothing" to "anon";

grant delete on table "public"."Clothing" to "authenticated";

grant insert on table "public"."Clothing" to "authenticated";

grant references on table "public"."Clothing" to "authenticated";

grant select on table "public"."Clothing" to "authenticated";

grant trigger on table "public"."Clothing" to "authenticated";

grant truncate on table "public"."Clothing" to "authenticated";

grant update on table "public"."Clothing" to "authenticated";

grant delete on table "public"."Clothing" to "service_role";

grant insert on table "public"."Clothing" to "service_role";

grant references on table "public"."Clothing" to "service_role";

grant select on table "public"."Clothing" to "service_role";

grant trigger on table "public"."Clothing" to "service_role";

grant truncate on table "public"."Clothing" to "service_role";

grant update on table "public"."Clothing" to "service_role";

grant delete on table "public"."Conversations" to "anon";

grant insert on table "public"."Conversations" to "anon";

grant references on table "public"."Conversations" to "anon";

grant select on table "public"."Conversations" to "anon";

grant trigger on table "public"."Conversations" to "anon";

grant truncate on table "public"."Conversations" to "anon";

grant update on table "public"."Conversations" to "anon";

grant delete on table "public"."Conversations" to "authenticated";

grant insert on table "public"."Conversations" to "authenticated";

grant references on table "public"."Conversations" to "authenticated";

grant select on table "public"."Conversations" to "authenticated";

grant trigger on table "public"."Conversations" to "authenticated";

grant truncate on table "public"."Conversations" to "authenticated";

grant update on table "public"."Conversations" to "authenticated";

grant delete on table "public"."Conversations" to "service_role";

grant insert on table "public"."Conversations" to "service_role";

grant references on table "public"."Conversations" to "service_role";

grant select on table "public"."Conversations" to "service_role";

grant trigger on table "public"."Conversations" to "service_role";

grant truncate on table "public"."Conversations" to "service_role";

grant update on table "public"."Conversations" to "service_role";

grant delete on table "public"."Groups" to "anon";

grant insert on table "public"."Groups" to "anon";

grant references on table "public"."Groups" to "anon";

grant select on table "public"."Groups" to "anon";

grant trigger on table "public"."Groups" to "anon";

grant truncate on table "public"."Groups" to "anon";

grant update on table "public"."Groups" to "anon";

grant delete on table "public"."Groups" to "authenticated";

grant insert on table "public"."Groups" to "authenticated";

grant references on table "public"."Groups" to "authenticated";

grant select on table "public"."Groups" to "authenticated";

grant trigger on table "public"."Groups" to "authenticated";

grant truncate on table "public"."Groups" to "authenticated";

grant update on table "public"."Groups" to "authenticated";

grant delete on table "public"."Groups" to "service_role";

grant insert on table "public"."Groups" to "service_role";

grant references on table "public"."Groups" to "service_role";

grant select on table "public"."Groups" to "service_role";

grant trigger on table "public"."Groups" to "service_role";

grant truncate on table "public"."Groups" to "service_role";

grant update on table "public"."Groups" to "service_role";

grant delete on table "public"."ItemConversions" to "anon";

grant insert on table "public"."ItemConversions" to "anon";

grant references on table "public"."ItemConversions" to "anon";

grant select on table "public"."ItemConversions" to "anon";

grant trigger on table "public"."ItemConversions" to "anon";

grant truncate on table "public"."ItemConversions" to "anon";

grant update on table "public"."ItemConversions" to "anon";

grant delete on table "public"."ItemConversions" to "authenticated";

grant insert on table "public"."ItemConversions" to "authenticated";

grant references on table "public"."ItemConversions" to "authenticated";

grant select on table "public"."ItemConversions" to "authenticated";

grant trigger on table "public"."ItemConversions" to "authenticated";

grant truncate on table "public"."ItemConversions" to "authenticated";

grant update on table "public"."ItemConversions" to "authenticated";

grant delete on table "public"."ItemConversions" to "service_role";

grant insert on table "public"."ItemConversions" to "service_role";

grant references on table "public"."ItemConversions" to "service_role";

grant select on table "public"."ItemConversions" to "service_role";

grant trigger on table "public"."ItemConversions" to "service_role";

grant truncate on table "public"."ItemConversions" to "service_role";

grant update on table "public"."ItemConversions" to "service_role";

grant delete on table "public"."Items" to "anon";

grant insert on table "public"."Items" to "anon";

grant references on table "public"."Items" to "anon";

grant select on table "public"."Items" to "anon";

grant trigger on table "public"."Items" to "anon";

grant truncate on table "public"."Items" to "anon";

grant update on table "public"."Items" to "anon";

grant delete on table "public"."Items" to "authenticated";

grant insert on table "public"."Items" to "authenticated";

grant references on table "public"."Items" to "authenticated";

grant select on table "public"."Items" to "authenticated";

grant trigger on table "public"."Items" to "authenticated";

grant truncate on table "public"."Items" to "authenticated";

grant update on table "public"."Items" to "authenticated";

grant delete on table "public"."Items" to "service_role";

grant insert on table "public"."Items" to "service_role";

grant references on table "public"."Items" to "service_role";

grant select on table "public"."Items" to "service_role";

grant trigger on table "public"."Items" to "service_role";

grant truncate on table "public"."Items" to "service_role";

grant update on table "public"."Items" to "service_role";

grant delete on table "public"."JoinRequests" to "anon";

grant insert on table "public"."JoinRequests" to "anon";

grant references on table "public"."JoinRequests" to "anon";

grant select on table "public"."JoinRequests" to "anon";

grant trigger on table "public"."JoinRequests" to "anon";

grant truncate on table "public"."JoinRequests" to "anon";

grant update on table "public"."JoinRequests" to "anon";

grant delete on table "public"."JoinRequests" to "authenticated";

grant insert on table "public"."JoinRequests" to "authenticated";

grant references on table "public"."JoinRequests" to "authenticated";

grant select on table "public"."JoinRequests" to "authenticated";

grant trigger on table "public"."JoinRequests" to "authenticated";

grant truncate on table "public"."JoinRequests" to "authenticated";

grant update on table "public"."JoinRequests" to "authenticated";

grant delete on table "public"."JoinRequests" to "service_role";

grant insert on table "public"."JoinRequests" to "service_role";

grant references on table "public"."JoinRequests" to "service_role";

grant select on table "public"."JoinRequests" to "service_role";

grant trigger on table "public"."JoinRequests" to "service_role";

grant truncate on table "public"."JoinRequests" to "service_role";

grant update on table "public"."JoinRequests" to "service_role";

grant delete on table "public"."Messages" to "anon";

grant insert on table "public"."Messages" to "anon";

grant references on table "public"."Messages" to "anon";

grant select on table "public"."Messages" to "anon";

grant trigger on table "public"."Messages" to "anon";

grant truncate on table "public"."Messages" to "anon";

grant update on table "public"."Messages" to "anon";

grant delete on table "public"."Messages" to "authenticated";

grant insert on table "public"."Messages" to "authenticated";

grant references on table "public"."Messages" to "authenticated";

grant select on table "public"."Messages" to "authenticated";

grant trigger on table "public"."Messages" to "authenticated";

grant truncate on table "public"."Messages" to "authenticated";

grant update on table "public"."Messages" to "authenticated";

grant delete on table "public"."Messages" to "service_role";

grant insert on table "public"."Messages" to "service_role";

grant references on table "public"."Messages" to "service_role";

grant select on table "public"."Messages" to "service_role";

grant trigger on table "public"."Messages" to "service_role";

grant truncate on table "public"."Messages" to "service_role";

grant update on table "public"."Messages" to "service_role";

grant delete on table "public"."Shoes" to "anon";

grant insert on table "public"."Shoes" to "anon";

grant references on table "public"."Shoes" to "anon";

grant select on table "public"."Shoes" to "anon";

grant trigger on table "public"."Shoes" to "anon";

grant truncate on table "public"."Shoes" to "anon";

grant update on table "public"."Shoes" to "anon";

grant delete on table "public"."Shoes" to "authenticated";

grant insert on table "public"."Shoes" to "authenticated";

grant references on table "public"."Shoes" to "authenticated";

grant select on table "public"."Shoes" to "authenticated";

grant trigger on table "public"."Shoes" to "authenticated";

grant truncate on table "public"."Shoes" to "authenticated";

grant update on table "public"."Shoes" to "authenticated";

grant delete on table "public"."Shoes" to "service_role";

grant insert on table "public"."Shoes" to "service_role";

grant references on table "public"."Shoes" to "service_role";

grant select on table "public"."Shoes" to "service_role";

grant trigger on table "public"."Shoes" to "service_role";

grant truncate on table "public"."Shoes" to "service_role";

grant update on table "public"."Shoes" to "service_role";

grant delete on table "public"."Wishlist" to "anon";

grant insert on table "public"."Wishlist" to "anon";

grant references on table "public"."Wishlist" to "anon";

grant select on table "public"."Wishlist" to "anon";

grant trigger on table "public"."Wishlist" to "anon";

grant truncate on table "public"."Wishlist" to "anon";

grant update on table "public"."Wishlist" to "anon";

grant delete on table "public"."Wishlist" to "authenticated";

grant insert on table "public"."Wishlist" to "authenticated";

grant references on table "public"."Wishlist" to "authenticated";

grant select on table "public"."Wishlist" to "authenticated";

grant trigger on table "public"."Wishlist" to "authenticated";

grant truncate on table "public"."Wishlist" to "authenticated";

grant update on table "public"."Wishlist" to "authenticated";

grant delete on table "public"."Wishlist" to "service_role";

grant insert on table "public"."Wishlist" to "service_role";

grant references on table "public"."Wishlist" to "service_role";

grant select on table "public"."Wishlist" to "service_role";

grant trigger on table "public"."Wishlist" to "service_role";

grant truncate on table "public"."Wishlist" to "service_role";

grant update on table "public"."Wishlist" to "service_role";


