

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


CREATE EXTENSION IF NOT EXISTS "pgsodium";






COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";






CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgjwt" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";






CREATE OR REPLACE FUNCTION "public"."handle_new_user"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    AS $$
begin
  insert into public.users (id)
  values (new.id);
  return new;
end;
$$;


ALTER FUNCTION "public"."handle_new_user"() OWNER TO "postgres";

SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."Accessories" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "itemId" bigint NOT NULL,
    "subcategory" "text" NOT NULL,
    "weight" "text" NOT NULL,
    "material" "text" NOT NULL,
    "condition" "text" NOT NULL,
    "color" "text" NOT NULL
);


ALTER TABLE "public"."Accessories" OWNER TO "postgres";


ALTER TABLE "public"."Accessories" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Accessories_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."CalendarDates" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "userId" "uuid" NOT NULL,
    "item" "text" NOT NULL,
    "itemType" "text" NOT NULL,
    "dates" "jsonb" NOT NULL
);


ALTER TABLE "public"."CalendarDates" OWNER TO "postgres";


ALTER TABLE "public"."CalendarDates" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."CalendarDates_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."Clothing" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "itemId" bigint NOT NULL,
    "subcategory" "text" NOT NULL,
    "size" "text" NOT NULL,
    "weight" "text" NOT NULL,
    "fabric" "text" NOT NULL,
    "condition" "text" NOT NULL,
    "color" "text" NOT NULL
);


ALTER TABLE "public"."Clothing" OWNER TO "postgres";


ALTER TABLE "public"."Clothing" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Clothing_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."Conversations" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "userId_1" "uuid",
    "userId_2" "uuid"
);


ALTER TABLE "public"."Conversations" OWNER TO "postgres";


ALTER TABLE "public"."Conversations" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Conversations_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."Groups" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "ambassadorId" "uuid" NOT NULL,
    "name" "text" NOT NULL,
    "description" "text" NOT NULL,
    "location" "text" NOT NULL,
    "rules" "text" NOT NULL,
    "numberOfMem" bigint NOT NULL,
    "avatar" "text" NOT NULL
);


ALTER TABLE "public"."Groups" OWNER TO "postgres";


ALTER TABLE "public"."Groups" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Groups_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."ItemConversions" (
    "id" bigint NOT NULL,
    "name" "text" NOT NULL,
    "litres" bigint NOT NULL,
    "carbon" double precision NOT NULL,
    "scalable" boolean NOT NULL,
    "category" "text"
);


ALTER TABLE "public"."ItemConversions" OWNER TO "postgres";


ALTER TABLE "public"."ItemConversions" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."ItemConversions_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."Items" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "userId" "uuid" NOT NULL,
    "category" "text" NOT NULL,
    "image" "text" NOT NULL,
    "title" "text" NOT NULL,
    "description" "text" NOT NULL,
    "method" "text" NOT NULL,
    "available" boolean DEFAULT true NOT NULL,
    "tradeCount" bigint DEFAULT '0'::bigint,
    "unavailableDates" "jsonb"
);


ALTER TABLE "public"."Items" OWNER TO "postgres";


ALTER TABLE "public"."Items" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Items_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."JoinRequests" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "userId" "uuid" NOT NULL,
    "groupId" bigint NOT NULL,
    "message" "text" DEFAULT ''::"text" NOT NULL,
    "status" "text" DEFAULT 'Pending'::"text" NOT NULL
);


ALTER TABLE "public"."JoinRequests" OWNER TO "postgres";


ALTER TABLE "public"."JoinRequests" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."JoinRequests_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."Messages" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "conversationId" bigint NOT NULL,
    "senderId" "uuid" NOT NULL,
    "text" "text",
    "itemId" bigint,
    "loanDates" "jsonb" DEFAULT 'null'::"jsonb",
    "messageType" "text" NOT NULL,
    "decision" "text"
);


ALTER TABLE "public"."Messages" OWNER TO "postgres";


ALTER TABLE "public"."Messages" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Messages_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."Shoes" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "itemId" bigint NOT NULL,
    "subcategory" "text" NOT NULL,
    "size" "text" NOT NULL,
    "weight" "text" NOT NULL,
    "fabric" "text" NOT NULL,
    "shoelength" "text" NOT NULL,
    "condition" "text" NOT NULL,
    "color" "text" NOT NULL
);


ALTER TABLE "public"."Shoes" OWNER TO "postgres";


ALTER TABLE "public"."Shoes" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Shoes_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."Wishlist" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "userId" "uuid",
    "itemId" bigint
);


ALTER TABLE "public"."Wishlist" OWNER TO "postgres";


ALTER TABLE "public"."Wishlist" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Wishlist_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE ONLY "public"."Accessories"
    ADD CONSTRAINT "Accessories_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."CalendarDates"
    ADD CONSTRAINT "CalendarDates_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."Conversations"
    ADD CONSTRAINT "Conversations_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."ItemConversions"
    ADD CONSTRAINT "ItemConversions_name_key" UNIQUE ("name");



ALTER TABLE ONLY "public"."ItemConversions"
    ADD CONSTRAINT "ItemConversions_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."Items"
    ADD CONSTRAINT "Items_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."JoinRequests"
    ADD CONSTRAINT "JoinRequests_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."Messages"
    ADD CONSTRAINT "Messages_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."Wishlist"
    ADD CONSTRAINT "Wishlist_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."Clothing"
    ADD CONSTRAINT "clothing_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."Groups"
    ADD CONSTRAINT "groups_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."Shoes"
    ADD CONSTRAINT "shoes_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."Accessories"
    ADD CONSTRAINT "Accessories_itemId_fkey" FOREIGN KEY ("itemId") REFERENCES "public"."Items"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."CalendarDates"
    ADD CONSTRAINT "CalendarDates_userId_fkey" FOREIGN KEY ("userId") REFERENCES "auth"."users"("id");



ALTER TABLE ONLY "public"."Conversations"
    ADD CONSTRAINT "Conversations_userId_1_fkey" FOREIGN KEY ("userId_1") REFERENCES "auth"."users"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."Conversations"
    ADD CONSTRAINT "Conversations_userId_2_fkey" FOREIGN KEY ("userId_2") REFERENCES "auth"."users"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."Items"
    ADD CONSTRAINT "Items_userId_fkey" FOREIGN KEY ("userId") REFERENCES "auth"."users"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."JoinRequests"
    ADD CONSTRAINT "JoinRequests_groupId_fkey" FOREIGN KEY ("groupId") REFERENCES "public"."Groups"("id") ON UPDATE CASCADE ON DELETE SET NULL;



ALTER TABLE ONLY "public"."JoinRequests"
    ADD CONSTRAINT "JoinRequests_userId_fkey" FOREIGN KEY ("userId") REFERENCES "auth"."users"("id") ON UPDATE CASCADE ON DELETE SET NULL;



ALTER TABLE ONLY "public"."Messages"
    ADD CONSTRAINT "Messages_conversationId_fkey" FOREIGN KEY ("conversationId") REFERENCES "public"."Conversations"("id");



ALTER TABLE ONLY "public"."Messages"
    ADD CONSTRAINT "Messages_itemId_fkey" FOREIGN KEY ("itemId") REFERENCES "public"."Items"("id");



ALTER TABLE ONLY "public"."Messages"
    ADD CONSTRAINT "Messages_senderId_fkey" FOREIGN KEY ("senderId") REFERENCES "auth"."users"("id");



ALTER TABLE ONLY "public"."Wishlist"
    ADD CONSTRAINT "Wishlist_itemId_fkey" FOREIGN KEY ("itemId") REFERENCES "public"."Items"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."Wishlist"
    ADD CONSTRAINT "Wishlist_userId_fkey" FOREIGN KEY ("userId") REFERENCES "auth"."users"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."Clothing"
    ADD CONSTRAINT "clothing_itemid_fkey" FOREIGN KEY ("itemId") REFERENCES "public"."Items"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."Groups"
    ADD CONSTRAINT "groups_ambassadorid_fkey" FOREIGN KEY ("ambassadorId") REFERENCES "auth"."users"("id") ON UPDATE CASCADE ON DELETE SET NULL;



ALTER TABLE ONLY "public"."Shoes"
    ADD CONSTRAINT "shoes_itemid_fkey" FOREIGN KEY ("itemId") REFERENCES "public"."Items"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE "public"."CalendarDates" ENABLE ROW LEVEL SECURITY;




ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";


GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";




















































































































































































GRANT ALL ON FUNCTION "public"."handle_new_user"() TO "anon";
GRANT ALL ON FUNCTION "public"."handle_new_user"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."handle_new_user"() TO "service_role";


















GRANT ALL ON TABLE "public"."Accessories" TO "anon";
GRANT ALL ON TABLE "public"."Accessories" TO "authenticated";
GRANT ALL ON TABLE "public"."Accessories" TO "service_role";



GRANT ALL ON SEQUENCE "public"."Accessories_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."Accessories_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Accessories_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."CalendarDates" TO "anon";
GRANT ALL ON TABLE "public"."CalendarDates" TO "authenticated";
GRANT ALL ON TABLE "public"."CalendarDates" TO "service_role";



GRANT ALL ON SEQUENCE "public"."CalendarDates_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."CalendarDates_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."CalendarDates_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."Clothing" TO "anon";
GRANT ALL ON TABLE "public"."Clothing" TO "authenticated";
GRANT ALL ON TABLE "public"."Clothing" TO "service_role";



GRANT ALL ON SEQUENCE "public"."Clothing_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."Clothing_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Clothing_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."Conversations" TO "anon";
GRANT ALL ON TABLE "public"."Conversations" TO "authenticated";
GRANT ALL ON TABLE "public"."Conversations" TO "service_role";



GRANT ALL ON SEQUENCE "public"."Conversations_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."Conversations_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Conversations_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."Groups" TO "anon";
GRANT ALL ON TABLE "public"."Groups" TO "authenticated";
GRANT ALL ON TABLE "public"."Groups" TO "service_role";



GRANT ALL ON SEQUENCE "public"."Groups_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."Groups_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Groups_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."ItemConversions" TO "anon";
GRANT ALL ON TABLE "public"."ItemConversions" TO "authenticated";
GRANT ALL ON TABLE "public"."ItemConversions" TO "service_role";



GRANT ALL ON SEQUENCE "public"."ItemConversions_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."ItemConversions_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."ItemConversions_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."Items" TO "anon";
GRANT ALL ON TABLE "public"."Items" TO "authenticated";
GRANT ALL ON TABLE "public"."Items" TO "service_role";



GRANT ALL ON SEQUENCE "public"."Items_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."Items_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Items_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."JoinRequests" TO "anon";
GRANT ALL ON TABLE "public"."JoinRequests" TO "authenticated";
GRANT ALL ON TABLE "public"."JoinRequests" TO "service_role";



GRANT ALL ON SEQUENCE "public"."JoinRequests_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."JoinRequests_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."JoinRequests_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."Messages" TO "anon";
GRANT ALL ON TABLE "public"."Messages" TO "authenticated";
GRANT ALL ON TABLE "public"."Messages" TO "service_role";



GRANT ALL ON SEQUENCE "public"."Messages_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."Messages_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Messages_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."Shoes" TO "anon";
GRANT ALL ON TABLE "public"."Shoes" TO "authenticated";
GRANT ALL ON TABLE "public"."Shoes" TO "service_role";



GRANT ALL ON SEQUENCE "public"."Shoes_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."Shoes_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Shoes_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."Wishlist" TO "anon";
GRANT ALL ON TABLE "public"."Wishlist" TO "authenticated";
GRANT ALL ON TABLE "public"."Wishlist" TO "service_role";



GRANT ALL ON SEQUENCE "public"."Wishlist_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."Wishlist_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Wishlist_id_seq" TO "service_role";



ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "service_role";






























RESET ALL;
